import type { Group } from "./api";

/**
 * Representative sample of NZ catchment / community / environmental groups used
 * as a fallback so the map is populated when the PHP API has no seed data (or is
 * offline). The live API response always takes precedence over this list.
 * Coordinates are approximate locality centroids, mirroring the public
 * landcare.org.nz catchments map (a national point layer of groups).
 */
export const sampleGroups: Group[] = [
  {
    id: "kaipara-moana-remediation",
    name: "Kaipara Moana Remediation",
    type: "catchment",
    region: "Northland",
    status: "active",
    focusAreas: ["water-quality", "riparian", "sediment"],
    description:
      "Cross-regional programme reducing sediment loss into the Kaipara Harbour through fencing, planting and erosion control.",
    website: "https://kaiparamoana.com",
    location: { lat: -36.05, lng: 174.12 },
  },
  {
    id: "whangarei-harbour-catchment",
    name: "Whangārei Harbour Catchment Group",
    type: "catchment",
    region: "Northland",
    status: "active",
    focusAreas: ["water-quality", "estuary"],
    description: "Landowners coordinating riparian restoration across the Whangārei Harbour catchment.",
    website: null,
    location: { lat: -35.76, lng: 174.36 },
  },
  {
    id: "pukekohe-east-catchment",
    name: "Pukekohe East Catchment Group",
    type: "catchment",
    region: "Auckland",
    status: "forming",
    focusAreas: ["water-quality", "soil"],
    description: "Growers and farmers forming a catchment collective in the Pukekohe vegetable-growing area.",
    website: null,
    location: { lat: -37.18, lng: 174.95 },
  },
  {
    id: "hunua-community-restoration",
    name: "Hunua Community Restoration",
    type: "community",
    region: "Auckland",
    status: "active",
    focusAreas: ["pest", "biodiversity"],
    description: "Volunteers restoring native bush and trapping predators in the Hunua Ranges.",
    website: null,
    location: { lat: -37.05, lng: 175.12 },
  },
  {
    id: "waikato-river-restoration",
    name: "Waikato River Restoration Group",
    type: "catchment",
    region: "Waikato",
    status: "active",
    focusAreas: ["water-quality", "riparian", "wetland"],
    description: "Restoring riparian margins and wetlands along the lower Waikato River.",
    website: null,
    location: { lat: -37.65, lng: 175.18 },
  },
  {
    id: "pokaiwhenua-catchment",
    name: "Pokaiwhenua Catchment Group",
    type: "catchment",
    region: "Waikato",
    status: "active",
    focusAreas: ["water-quality", "biodiversity"],
    description: "Farmer-led catchment group improving water quality in the Pokaiwhenua Stream.",
    website: null,
    location: { lat: -38.02, lng: 175.78 },
  },
  {
    id: "maungatautari-sanctuary",
    name: "Sanctuary Mountain Maungatautari",
    type: "environmental",
    region: "Waikato",
    status: "active",
    focusAreas: ["pest", "biodiversity"],
    description: "Pest-fenced ecological island restoring native species on Maungatautari.",
    website: "https://www.sanctuarymountain.co.nz",
    location: { lat: -38.05, lng: 175.56 },
  },
  {
    id: "kaituna-catchment-collective",
    name: "Kaituna Catchment Collective",
    type: "catchment",
    region: "Bay of Plenty",
    status: "active",
    focusAreas: ["water-quality", "wetland", "estuary"],
    description: "Coordinating wetland restoration and re-diversion work across the Kaituna catchment.",
    website: null,
    location: { lat: -37.79, lng: 176.4 },
  },
  {
    id: "uretara-estuary-managers",
    name: "Uretara Estuary Managers",
    type: "community",
    region: "Bay of Plenty",
    status: "active",
    focusAreas: ["estuary", "water-quality", "riparian"],
    description: "Katikati community group restoring the Uretara Stream and estuary.",
    website: null,
    location: { lat: -37.55, lng: 175.92 },
  },
  {
    id: "gisborne-waiapu-catchment",
    name: "Waiapu Catchment Group",
    type: "catchment",
    region: "Gisborne",
    status: "active",
    focusAreas: ["sediment", "erosion", "riparian"],
    description: "Addressing severe hill-country erosion and sediment in the Waiapu catchment.",
    website: null,
    location: { lat: -37.79, lng: 178.33 },
  },
  {
    id: "tutaekuri-catchment",
    name: "Tūtaekurī Catchment Group",
    type: "catchment",
    region: "Hawke's Bay",
    status: "active",
    focusAreas: ["water-quality", "riparian"],
    description: "Hawke's Bay landowners restoring the Tūtaekurī River margins after Cyclone Gabrielle.",
    website: null,
    location: { lat: -39.53, lng: 176.74 },
  },
  {
    id: "ahuriri-estuary-protection",
    name: "Ahuriri Estuary Protection Society",
    type: "environmental",
    region: "Hawke's Bay",
    status: "active",
    focusAreas: ["estuary", "biodiversity", "water-quality"],
    description: "Protecting and restoring the Ahuriri Estuary / Te Whanganui-a-Orotū.",
    website: null,
    location: { lat: -39.48, lng: 176.88 },
  },
  {
    id: "taranaki-waiwhakaiho",
    name: "Waiwhakaiho Catchment Group",
    type: "catchment",
    region: "Taranaki",
    status: "forming",
    focusAreas: ["water-quality", "riparian"],
    description: "New Plymouth landowners forming a catchment group on the Waiwhakaiho River.",
    website: null,
    location: { lat: -39.06, lng: 174.13 },
  },
  {
    id: "manawatu-river-leaders",
    name: "Manawatū River Leaders' Forum",
    type: "catchment",
    region: "Manawatū-Whanganui",
    status: "active",
    focusAreas: ["water-quality", "riparian", "wetland"],
    description: "Multi-stakeholder accord improving the health of the Manawatū River.",
    website: null,
    location: { lat: -40.36, lng: 175.61 },
  },
  {
    id: "whanganui-awa-restoration",
    name: "Whanganui Awa Restoration",
    type: "community",
    region: "Manawatū-Whanganui",
    status: "active",
    focusAreas: ["riparian", "biodiversity"],
    description: "Community planting and pest control along the Whanganui River.",
    website: null,
    location: { lat: -39.93, lng: 175.05 },
  },
  {
    id: "wairarapa-pukaha-to-kawakawa",
    name: "Pūkaha to Kawakawa Alliance",
    type: "environmental",
    region: "Wellington",
    status: "active",
    focusAreas: ["pest", "biodiversity", "riparian"],
    description: "Landscape-scale predator control connecting Pūkaha to the Wairarapa coast.",
    website: null,
    location: { lat: -40.77, lng: 175.65 },
  },
  {
    id: "porirua-harbour-catchment",
    name: "Porirua Harbour & Catchment Group",
    type: "catchment",
    region: "Wellington",
    status: "active",
    focusAreas: ["water-quality", "estuary", "sediment"],
    description: "Whaitua-based group reducing sediment and contaminants entering Porirua Harbour.",
    website: null,
    location: { lat: -41.1, lng: 174.85 },
  },
  {
    id: "wainuiomata-catchment-care",
    name: "Wainuiomata Catchment Care",
    type: "community",
    region: "Wellington",
    status: "forming",
    focusAreas: ["riparian", "pest"],
    description: "Residents restoring the Wainuiomata River corridor.",
    website: null,
    location: { lat: -41.27, lng: 174.95 },
  },
  {
    id: "top-of-the-south-marlborough-sounds",
    name: "Marlborough Sounds Restoration Trust",
    type: "environmental",
    region: "Marlborough",
    status: "active",
    focusAreas: ["biodiversity", "pest", "estuary"],
    description: "Restoring native forest and reducing pests across the Marlborough Sounds.",
    website: null,
    location: { lat: -41.13, lng: 174.0 },
  },
  {
    id: "motueka-catchment-collective",
    name: "Motueka Catchment Collective",
    type: "catchment",
    region: "Tasman",
    status: "active",
    focusAreas: ["water-quality", "riparian", "biodiversity"],
    description: "Tasman growers and farmers improving the Motueka River catchment.",
    website: null,
    location: { lat: -41.11, lng: 172.99 },
  },
  {
    id: "waimea-inlet-forum",
    name: "Waimea Inlet Forum",
    type: "environmental",
    region: "Tasman",
    status: "active",
    focusAreas: ["estuary", "biodiversity", "water-quality"],
    description: "Coordinating restoration around the Waimea Inlet, the largest enclosed estuary in the South Island.",
    website: null,
    location: { lat: -41.31, lng: 173.13 },
  },
  {
    id: "maitai-river-catchment",
    name: "Maitai / Mahitahi Catchment Group",
    type: "catchment",
    region: "Nelson",
    status: "forming",
    focusAreas: ["water-quality", "riparian"],
    description: "Nelson community forming a catchment group for the Maitai / Mahitahi River.",
    website: null,
    location: { lat: -41.27, lng: 173.32 },
  },
  {
    id: "hurunui-catchment-group",
    name: "Hurunui District Landcare Group",
    type: "catchment",
    region: "Canterbury",
    status: "active",
    focusAreas: ["water-quality", "biodiversity", "pest"],
    description: "Long-running North Canterbury group coordinating biodiversity and water-quality work.",
    website: null,
    location: { lat: -42.74, lng: 172.55 },
  },
  {
    id: "selwyn-waihora",
    name: "Selwyn–Waihora Catchment Group",
    type: "catchment",
    region: "Canterbury",
    status: "active",
    focusAreas: ["water-quality", "wetland", "biodiversity"],
    description: "Reducing nutrient losses across the Selwyn–Te Waihora (Lake Ellesmere) catchment.",
    website: null,
    location: { lat: -43.65, lng: 172.3 },
  },
  {
    id: "opihi-river-catchment",
    name: "Ōpihi River Catchment Group",
    type: "catchment",
    region: "Canterbury",
    status: "active",
    focusAreas: ["water-quality", "riparian"],
    description: "South Canterbury landowners improving flows and water quality in the Ōpihi.",
    website: null,
    location: { lat: -44.25, lng: 171.15 },
  },
  {
    id: "avon-heathcote-estuary",
    name: "Avon-Heathcote Estuary Ihutai Trust",
    type: "environmental",
    region: "Canterbury",
    status: "active",
    focusAreas: ["estuary", "biodiversity", "water-quality"],
    description: "Christchurch trust restoring the Avon-Heathcote Estuary / Ihutai.",
    website: null,
    location: { lat: -43.55, lng: 172.74 },
  },
  {
    id: "north-otago-sustainable-land",
    name: "North Otago Sustainable Land Management",
    type: "catchment",
    region: "Otago",
    status: "active",
    focusAreas: ["soil", "water-quality", "biodiversity"],
    description: "Farmer group promoting sustainable land use across the Waitaki and North Otago.",
    website: null,
    location: { lat: -45.1, lng: 170.97 },
  },
  {
    id: "pomahaka-water-care",
    name: "Pomahaka Water Care Group",
    type: "catchment",
    region: "Otago",
    status: "active",
    focusAreas: ["water-quality", "riparian"],
    description: "Award-winning West Otago group monitoring and improving the Pomahaka River.",
    website: null,
    location: { lat: -45.9, lng: 169.36 },
  },
  {
    id: "dunedin-town-belt-kaitiaki",
    name: "Ōtepoti Town Belt Kaitiaki",
    type: "community",
    region: "Otago",
    status: "forming",
    focusAreas: ["pest", "biodiversity"],
    description: "Dunedin volunteers restoring native habitat in the Town Belt.",
    website: null,
    location: { lat: -45.86, lng: 170.5 },
  },
  {
    id: "aparima-catchment-group",
    name: "Aparima Catchment Group",
    type: "catchment",
    region: "Southland",
    status: "active",
    focusAreas: ["water-quality", "riparian", "wetland"],
    description: "Whole-of-catchment community project improving the Aparima River.",
    website: null,
    location: { lat: -46.0, lng: 168.0 },
  },
  {
    id: "waituna-lagoon-partnership",
    name: "Waituna Lagoon Partnership",
    type: "environmental",
    region: "Southland",
    status: "active",
    focusAreas: ["wetland", "water-quality", "biodiversity"],
    description: "Protecting the internationally significant Waituna Lagoon Ramsar wetland.",
    website: null,
    location: { lat: -46.55, lng: 168.6 },
  },
  {
    id: "west-coast-grey-catchment",
    name: "Grey River / Māwheranui Catchment Group",
    type: "catchment",
    region: "West Coast",
    status: "forming",
    focusAreas: ["water-quality", "biodiversity"],
    description: "West Coast landowners forming a catchment group for the Grey River.",
    website: null,
    location: { lat: -42.45, lng: 171.21 },
  },
];
